import type { LanguageLevel } from '@/types/index';
import type { WotdWord } from '@/lib/wordOfTheDay';

/**
 * Curated, high-yield vocabulary sets across all CEFR levels (A1 to C1).
 * 100% English deterministic daily catalog for zero latency.
 */
export const CURATED_WOTD_SETS: Record<LanguageLevel, WotdWord[]> = {
  A1: [
    {
      word: 'welcome',
      arabicMeaning: 'To greet someone warmly upon arrival',
      englishDefinition: 'To greet someone who has just arrived in a friendly and polite way.',
      ipa: '/ˈwel.kəm/',
      emojiAnchor: 'Sparkles',
      memoryTip: 'Think of greeting a close friend at your door with open arms and a warm smile.',
      collocations: ['warm welcome', 'feel welcome', 'welcome home'],
      frequencyNote: 'common',
      exampleSentence: 'They gave us a very warm ___ when we arrived.',
    },
    {
      word: 'journey',
      arabicMeaning: 'An act of traveling from one place to another',
      englishDefinition: 'An act of traveling from one place to another over a distance.',
      ipa: '/ˈdʒɜː.ni/',
      emojiAnchor: 'Compass',
      memoryTip: 'Picture an adventurous road trip with friends across scenic mountains.',
      collocations: ['safe journey', 'long journey', 'start a journey'],
      frequencyNote: 'common',
      exampleSentence: 'Have a safe ___ back home!',
    },
    {
      word: 'delicious',
      arabicMeaning: 'Extremely pleasant to taste',
      englishDefinition: 'Having a very pleasant and enjoyable taste or smell.',
      ipa: '/dɪˈlɪʃ.əs/',
      emojiAnchor: 'Sparkles',
      memoryTip: 'Think of your favorite home-cooked meal right when you take the first bite.',
      collocations: ['delicious food', 'delicious meal', 'smells delicious'],
      frequencyNote: 'common',
      exampleSentence: 'This home-cooked dinner is absolutely ___.',
    },
    {
      word: 'celebrate',
      arabicMeaning: 'To observe a notable event with festivities',
      englishDefinition: 'To do something enjoyable because of a special day or event.',
      ipa: '/ˈsel.ə.breɪt/',
      emojiAnchor: 'Trophy',
      memoryTip: 'Picture a joyful graduation party or birthday gathering with cheering friends.',
      collocations: ['celebrate a birthday', 'celebrate success', 'celebrate with friends'],
      frequencyNote: 'common',
      exampleSentence: 'We went out to a nice dinner to ___ his promotion.',
    },
    {
      word: 'friendly',
      arabicMeaning: 'Kind, pleasant, and helpful',
      englishDefinition: 'Behaving in a pleasant, kind, and helpful way towards people.',
      ipa: '/ˈfrend.li/',
      emojiAnchor: 'Heart',
      memoryTip: 'Root word: Friend. Someone who treats everyone with genuine warmth.',
      collocations: ['friendly smile', 'friendly atmosphere', 'warm and friendly'],
      frequencyNote: 'common',
      exampleSentence: 'The hotel staff were extremely polite and ___.',
    },
    {
      word: 'discover',
      arabicMeaning: 'To find or learn something new',
      englishDefinition: 'To find or learn about something for the very first time.',
      ipa: '/dɪˈskʌv.ər/',
      emojiAnchor: 'Search',
      memoryTip: 'Think of uncovering a hidden treasure or finding a brand new favorite song.',
      collocations: ['discover a place', 'discover the truth', 'discover a talent'],
      frequencyNote: 'common',
      exampleSentence: 'Scientists continue to ___ new species in the ocean.',
    },
    {
      word: 'explore',
      arabicMeaning: 'To travel through an unfamiliar area to learn about it',
      englishDefinition: 'To travel around a new area in order to learn about it.',
      ipa: '/ɪkˈsplɔːr/',
      emojiAnchor: 'Map',
      memoryTip: 'Think of walking through historic city streets discovering local secrets.',
      collocations: ['explore the city', 'explore options', 'explore the world'],
      frequencyNote: 'common',
      exampleSentence: 'We spent the entire afternoon ___ing old historic streets.',
    },
  ],
  A2: [
    {
      word: 'encourage',
      arabicMeaning: 'To give support, confidence, or hope',
      englishDefinition: 'To give someone support, confidence, or hope to do something.',
      ipa: '/ɪnˈkʌr.ɪdʒ/',
      emojiAnchor: 'Award',
      memoryTip: 'En + Courage: Pouring courage into someone so they keep moving forward.',
      collocations: ['encourage someone to', 'strongly encourage', 'words of encouragement'],
      frequencyNote: 'common',
      exampleSentence: 'My mentor always ___s me to speak English without fear.',
    },
    {
      word: 'improve',
      arabicMeaning: 'To make or become better',
      englishDefinition: 'To make or become better in quality, skill, or condition.',
      ipa: '/ɪmˈpruːv/',
      emojiAnchor: 'TrendingUp',
      memoryTip: 'Think of leveling up in a game: daily consistency leads to visible mastery.',
      collocations: ['improve skills', 'improve performance', 'dramatically improve'],
      frequencyNote: 'common',
      exampleSentence: 'Daily practice will quickly ___ your English speaking.',
    },
    {
      word: 'convenient',
      arabicMeaning: 'Fitting in well with needs or plans',
      englishDefinition: 'Fitting in well with a person’s needs, activities, and plans.',
      ipa: '/kənˈviː.ni.ənt/',
      emojiAnchor: 'CheckCircle',
      memoryTip: 'Think of a grocery store right next to your doorstep: effortless and accessible.',
      collocations: ['convenient time', 'convenient location', 'easy and convenient'],
      frequencyNote: 'common',
      exampleSentence: 'Online tools are very fast and ___ for busy professionals.',
    },
    {
      word: 'opportunity',
      arabicMeaning: 'A favorable time or chance for progress',
      englishDefinition: 'A set of circumstances that makes it possible to do something.',
      ipa: '/ˌɒp.əˈtʃuː.nə.ti/',
      emojiAnchor: 'Zap',
      memoryTip: 'Think of an open door to your dream career: ready for you to step through.',
      collocations: ['golden opportunity', 'miss an opportunity', 'grab an opportunity'],
      frequencyNote: 'common',
      exampleSentence: 'This role is an amazing ___ to learn advanced leadership skills.',
    },
    {
      word: 'patient',
      arabicMeaning: 'Able to tolerate delay without anger',
      englishDefinition: 'Able to accept delays or problems without becoming annoyed or anxious.',
      ipa: '/ˈpeɪ.ʃənt/',
      emojiAnchor: 'Shield',
      memoryTip: 'Language fluency is a marathon, not a sprint: remain steady and calm.',
      collocations: ['be patient with', 'patient listener', 'remain patient'],
      frequencyNote: 'common',
      exampleSentence: 'Learning a language takes practice, so be ___ with yourself.',
    },
    {
      word: 'protect',
      arabicMeaning: 'To keep safe from harm or injury',
      englishDefinition: 'To keep someone or something safe from harm, damage, or illness.',
      ipa: '/prəˈtekt/',
      emojiAnchor: 'Shield',
      memoryTip: 'Think of a sturdy shield protecting a castle against harsh storms.',
      collocations: ['protect against', 'protect the environment', 'protect privacy'],
      frequencyNote: 'common',
      exampleSentence: 'Use strong passwords to ___ your personal accounts online.',
    },
  ],
  B1: [
    {
      word: 'hesitate',
      arabicMeaning: 'To pause before action due to doubt',
      englishDefinition: 'To pause before doing or saying something because you are uncertain.',
      ipa: '/ˈhez.ɪ.teɪt/',
      emojiAnchor: 'Clock',
      memoryTip: 'Standing at a doorway wondering whether to step inside. Take the leap!',
      collocations: ['do not hesitate to', 'hesitate for a moment', 'without hesitation'],
      frequencyNote: 'common',
      exampleSentence: 'Please do not ___ to reach out if you have any questions.',
    },
    {
      word: 'fluent',
      arabicMeaning: 'Able to express oneself easily and articulately',
      englishDefinition: 'Able to speak or write a particular foreign language easily and accurately.',
      ipa: '/ˈfluː.ənt/',
      emojiAnchor: 'Sparkles',
      memoryTip: 'Root: Flow (like a river). Words streaming effortlessly without pauses.',
      collocations: ['fluent in English', 'speak fluently', 'become fluent'],
      frequencyNote: 'common',
      exampleSentence: 'She practiced daily until she became fully ___ in English.',
    },
    {
      word: 'accomplish',
      arabicMeaning: 'To achieve or complete successfully',
      englishDefinition: 'To achieve or complete successfully something you planned.',
      ipa: '/əˈkʌm.plɪʃ/',
      emojiAnchor: 'CheckCircle',
      memoryTip: 'Mission Accomplished! Crossing the finish line of a major long-term project.',
      collocations: ['accomplish a goal', 'accomplish a task', 'sense of accomplishment'],
      frequencyNote: 'common',
      exampleSentence: 'You can ___ great things if you stay consistent every single day.',
    },
    {
      word: 'struggle',
      arabicMeaning: 'To strive or make strenuous efforts in the face of difficulties',
      englishDefinition: 'To try very hard to do something when it is difficult.',
      ipa: '/ˈstrʌɡ.əl/',
      emojiAnchor: 'Activity',
      memoryTip: 'Climbing a steep mountain trail: demanding effort that builds strength.',
      collocations: ['struggle with', 'struggle to understand', 'real struggle'],
      frequencyNote: 'common',
      exampleSentence: 'Many learners ___ with prepositions at first, but practice solves it.',
    },
    {
      word: 'reliable',
      arabicMeaning: 'Consistently good and trustworthy',
      englishDefinition: 'Consistently good in quality or performance; able to be trusted.',
      ipa: '/rɪˈlaɪ.ə.bəl/',
      emojiAnchor: 'Shield',
      memoryTip: 'Rely-able: A loyal teammate who delivers on every promise on time.',
      collocations: ['reliable source', 'reliable person', 'highly reliable'],
      frequencyNote: 'common',
      exampleSentence: 'Omar is a very ___ team member who always exceeds expectations.',
    },
    {
      word: 'essential',
      arabicMeaning: 'Absolutely necessary and indispensable',
      englishDefinition: 'Extremely important and completely necessary for something to work.',
      ipa: '/ɪˈsen.ʃəl/',
      emojiAnchor: 'Key',
      memoryTip: 'The core essence of life: like oxygen or water, you cannot do without it.',
      collocations: ['essential role', 'essential part', 'essential skill'],
      frequencyNote: 'common',
      exampleSentence: 'Clear communication is an ___ skill in any modern workplace.',
    },
  ],
  B2: [
    {
      word: 'resilient',
      arabicMeaning: 'Able to recover quickly from setbacks',
      englishDefinition: 'Able to recover quickly from difficult situations, setbacks, or shocks.',
      ipa: '/rɪˈzɪl.jənt/',
      emojiAnchor: 'Sparkles',
      memoryTip: 'A bamboo tree in strong winds: bends flexibly without breaking, then bounces back.',
      collocations: ['resilient attitude', 'remain resilient', 'build resilience'],
      frequencyNote: 'common',
      exampleSentence: 'Great founders must be ___ when navigating unexpected market shifts.',
    },
    {
      word: 'articulate',
      arabicMeaning: 'Expressing ideas clearly and effectively',
      englishDefinition: 'Expressing ideas clearly, fluently, and effectively in speech or writing.',
      ipa: '/ɑːˈtɪk.jə.lət/',
      emojiAnchor: 'Mic',
      memoryTip: 'Every joint and phrase connected seamlessly with crystal-clear clarity.',
      collocations: ['articulate speaker', 'articulate an idea', 'clear and articulate'],
      frequencyNote: 'formal',
      exampleSentence: 'She gave an ___ presentation that convinced the entire executive panel.',
    },
    {
      word: 'compelling',
      arabicMeaning: 'Irresistibly convincing and captivating',
      englishDefinition: 'Evoking interest, attention, or admiration in a powerfully irresistible way.',
      ipa: '/kəmˈpel.ɪŋ/',
      emojiAnchor: 'Star',
      memoryTip: 'A plot twist in a gripping novel that compels you to keep reading all night.',
      collocations: ['compelling argument', 'compelling story', 'compelling reason'],
      frequencyNote: 'common',
      exampleSentence: 'The researcher presented a ___ case for next-generation clean energy.',
    },
    {
      word: 'meticulous',
      arabicMeaning: 'Showing extreme care and precision',
      englishDefinition: 'Showing great attention to detail; very careful and precise.',
      ipa: '/məˈtɪk.jə.ləs/',
      emojiAnchor: 'Search',
      memoryTip: 'Like a master watchmaker aligning every microscopic gear with precision.',
      collocations: ['meticulous planning', 'meticulous attention', 'meticulous research'],
      frequencyNote: 'formal',
      exampleSentence: 'Her ___ preparation was the main secret behind the product launch success.',
    },
    {
      word: 'proactive',
      arabicMeaning: 'Taking initiative before events unfold',
      englishDefinition: 'Creating or controlling a situation rather than just responding to it after it happened.',
      ipa: '/prəʊˈæk.tɪv/',
      emojiAnchor: 'Rocket',
      memoryTip: 'Antonym of Reactive: Steering the ship proactively rather than drifting with waves.',
      collocations: ['proactive approach', 'take proactive steps', 'proactive mindset'],
      frequencyNote: 'common',
      exampleSentence: 'Taking a ___ approach to preparation eliminates last-minute panic.',
    },
    {
      word: 'lucid',
      arabicMeaning: 'Crystal clear and easy to understand',
      englishDefinition: 'Expressed clearly; easy to understand without any ambiguity or confusion.',
      ipa: '/ˈluː.sɪd/',
      emojiAnchor: 'Sun',
      memoryTip: 'Root: Luc (light). A concept illuminated so brightly that understanding is instant.',
      collocations: ['lucid explanation', 'lucid account', 'clear and lucid'],
      frequencyNote: 'formal',
      exampleSentence: 'The professor provided a ___ explanation of a complex quantum theorem.',
    },
  ],
  C1: [
    {
      word: 'serendipity',
      arabicMeaning: 'The occurrence of valuable discoveries by happy chance',
      englishDefinition: 'The occurrence of events by chance in a happy, beneficial, or fortunate way.',
      ipa: '/ˌser.ənˈdɪp.ə.ti/',
      emojiAnchor: 'Sparkles',
      memoryTip: 'Stumbling upon a life-changing book while casually browsing an old library shelf.',
      collocations: ['pure serendipity', 'happy serendipity', 'moment of serendipity'],
      frequencyNote: 'formal',
      exampleSentence: 'Meeting my current business partner at an airport lounge was pure ___.',
    },
    {
      word: 'eloquent',
      arabicMeaning: 'Expressing ideas with powerful and graceful style',
      englishDefinition: 'Fluent or persuasive in speaking or writing with elegance and grace.',
      ipa: '/ˈel.ə.kwənt/',
      emojiAnchor: 'Feather',
      memoryTip: 'A masterful orator whose words captivate the mind and stir deep emotions.',
      collocations: ['eloquent speech', 'eloquent writer', 'eloquently expressed'],
      frequencyNote: 'formal',
      exampleSentence: 'He delivered an ___ keynote that moved the entire auditorium.',
    },
    {
      word: 'ubiquitous',
      arabicMeaning: 'Present, appearing, or found everywhere',
      englishDefinition: 'Present, appearing, or found everywhere at the same time.',
      ipa: '/juːˈbɪk.wɪ.təs/',
      emojiAnchor: 'Globe',
      memoryTip: 'Ubique (everywhere): Like mobile signals or internet access in modern society.',
      collocations: ['ubiquitous presence', 'become ubiquitous', 'almost ubiquitous'],
      frequencyNote: 'specialized',
      exampleSentence: 'Cloud computing has become truly ___ across modern industry stacks.',
    },
    {
      word: 'ephemeral',
      arabicMeaning: 'Lasting for a very brief period',
      englishDefinition: 'Lasting for a very short period of time; fleeting.',
      ipa: '/ɪˈfem.ər.əl/',
      emojiAnchor: 'Clock',
      memoryTip: 'A brilliant rainbow or morning dew: exquisite beauty that lasts only moments.',
      collocations: ['ephemeral beauty', 'ephemeral nature', 'fleeting and ephemeral'],
      frequencyNote: 'specialized',
      exampleSentence: 'Viral social media trends are often ___, fading within days.',
    },
    {
      word: 'pragmatic',
      arabicMeaning: 'Dealing with matters sensibly and realistically',
      englishDefinition: 'Dealing with things sensibly and realistically based on practical considerations.',
      ipa: '/præɡˈmæt.ɪk/',
      emojiAnchor: 'Settings',
      memoryTip: 'Focusing on actionable solutions that deliver tangible results in the real world.',
      collocations: ['pragmatic solution', 'pragmatic approach', 'pragmatic leader'],
      frequencyNote: 'common',
      exampleSentence: 'We chose a ___ architectural roadmap that allowed us to ship faster.',
    },
    {
      word: 'paradigm',
      arabicMeaning: 'A distinct concept, pattern, or model',
      englishDefinition: 'A typical example, pattern, or framework of ideas and concepts.',
      ipa: '/ˈpær.ə.daɪm/',
      emojiAnchor: 'Layers',
      memoryTip: 'Paradigm Shift: A fundamental transformation in how an entire field thinks and acts.',
      collocations: ['paradigm shift', 'dominant paradigm', 'new paradigm'],
      frequencyNote: 'specialized',
      exampleSentence: 'Generative AI represents a profound ___ shift in software engineering.',
    },
  ],
};

/**
 * Gets a deterministic daily set based on today's date hash.
 */
export function getCuratedDailyWotdSet(dateString = new Date().toISOString().slice(0, 10)) {
  let hash = 0;
  for (let i = 0; i < dateString.length; i++) {
    hash = (hash << 5) - hash + dateString.charCodeAt(i);
    hash |= 0;
  }
  const positiveHash = Math.abs(hash);

  return {
    date: dateString,
    words: {
      A1: CURATED_WOTD_SETS.A1[positiveHash % CURATED_WOTD_SETS.A1.length],
      A2: CURATED_WOTD_SETS.A2[positiveHash % CURATED_WOTD_SETS.A2.length],
      B1: CURATED_WOTD_SETS.B1[positiveHash % CURATED_WOTD_SETS.B1.length],
      B2: CURATED_WOTD_SETS.B2[positiveHash % CURATED_WOTD_SETS.B2.length],
      C1: CURATED_WOTD_SETS.C1[positiveHash % CURATED_WOTD_SETS.C1.length],
    },
  };
}
