import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { AnimatePresence, motion } from 'framer-motion';
import {
  ChevronLeft,
  ChevronRight,
  Loader2,
  Play,
  RefreshCw,
  RotateCcw,
  SkipBack,
  SkipForward,
  Subtitles,
  X,
} from 'lucide-react';

/* ─── Video search (keyless YouTube search via public Piped instances) ──────── */

interface VideoResult {
  id: string;
  title: string;
  uploader: string;
}

const PIPED_INSTANCES = [
  'https://api.piped.private.coffee',
  'https://pipedapi.adminforge.de',
  'https://pipedapi.kavin.rocks',
  'https://pipedapi.leptons.xyz',
];

async function pipedFetch<T>(path: string): Promise<T> {
  let lastError: unknown = null;
  for (const base of PIPED_INSTANCES) {
    try {
      const res = await fetch(`${base}${path}`, { signal: AbortSignal.timeout(10000) });
      if (!res.ok) throw new Error(String(res.status));
      return (await res.json()) as T;
    } catch (err) {
      lastError = err;
    }
  }
  throw lastError ?? new Error('all instances failed');
}

async function searchVideos(query: string): Promise<VideoResult[]> {
  const data = await pipedFetch<{
    items?: Array<{ url?: string; title?: string; uploaderName?: string }>;
  }>(`/search?q=${encodeURIComponent(query)}&filter=videos`);
  const videos = (data.items ?? [])
    .map(it => ({
      id: (it.url ?? '').split('v=')[1] ?? '',
      title: it.title ?? '',
      uploader: it.uploaderName ?? '',
    }))
    .filter(v => v.id && v.title);
  if (videos.length === 0) throw new Error('no results');
  return videos;
}

/* ─── Word timing from subtitles ────────────────────────────────────────────── */

function parseVttStart(vtt: string, word: string): number | null {
  const re = new RegExp(`\\b${word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'i');
  const blocks = vtt.split(/\r?\n\r?\n/);
  for (const block of blocks) {
    const lines = block.split(/\r?\n/);
    const timeLine = lines.find(l => l.includes('-->'));
    if (!timeLine) continue;
    const match = timeLine.match(/(\d{1,2}):(\d{2}):(\d{2})[.,]\d{3}\s*-->/);
    if (!match) continue;
    const text = lines
      .slice(lines.indexOf(timeLine) + 1)
      .join(' ')
      .replace(/<[^>]+>/g, '');
    if (re.test(text)) {
      const secs = Number(match[1]) * 3600 + Number(match[2]) * 60 + Number(match[3]);
      return Math.max(0, secs - 2);
    }
  }
  return null;
}

/** Finds the first caption timestamp where the word is spoken */
async function findWordTime(videoId: string, word: string): Promise<number | null> {
  try {
    const data = await pipedFetch<{
      subtitles?: Array<{ url?: string; code?: string; autoGenerated?: boolean }>;
    }>(`/streams/${videoId}`);
    const subs = data.subtitles ?? [];
    const ordered = [
      ...subs.filter(s => s.code?.startsWith('en') && !s.autoGenerated),
      ...subs.filter(s => s.code?.startsWith('en') && s.autoGenerated),
    ];
    for (const sub of ordered.slice(0, 3)) {
      if (!sub.url) continue;
      const res = await fetch(sub.url, { signal: AbortSignal.timeout(10000) });
      if (!res.ok) continue;
      const vtt = await res.text();
      const t = parseVttStart(vtt, word);
      if (t !== null) return t;
    }
  } catch {
    /* fall back to start of video */
  }
  return null;
}

/* ─── YouTube IFrame API glue ───────────────────────────────────────────────── */

interface YTPlayer {
  loadVideoById: (opts: { videoId: string; startSeconds?: number }) => void;
  seekTo: (seconds: number, allowSeekAhead: boolean) => void;
  playVideo: () => void;
  destroy: () => void;
}

interface YTApi {
  Player: new (
    element: HTMLElement,
    opts: {
      videoId: string;
      playerVars: Record<string, string | number>;
      events?: { onReady?: () => void };
    }
  ) => YTPlayer;
}

declare global {
  interface Window {
    YT?: YTApi;
    onYouTubeIframeAPIReady?: () => void;
  }
}

let ytLoadPromise: Promise<void> | null = null;

function loadYouTubeApi(): Promise<void> {
  if (typeof window === 'undefined') return Promise.reject(new Error('no window'));
  if (window.YT?.Player) return Promise.resolve();
  if (ytLoadPromise) return ytLoadPromise;

  ytLoadPromise = new Promise(resolve => {
    const prev = window.onYouTubeIframeAPIReady;
    window.onYouTubeIframeAPIReady = () => {
      prev?.();
      resolve();
    };
    const tag = document.createElement('script');
    tag.src = 'https://www.youtube.com/iframe_api';
    document.head.appendChild(tag);
  });
  return ytLoadPromise;
}

/* ─── Modal ─────────────────────────────────────────────────────────────────── */

interface WordVideosModalProps {
  word: string;
  onClose: () => void;
}

/**
 * In-app video popup — our own YouGlish replacement. Searches real videos
 * containing the word, starts playing at the moment the word is spoken,
 * supports replay / ±5s seeking and shows subtitles.
 */
export function WordVideosModal({ word, onClose }: WordVideosModalProps) {
  const [videos, setVideos] = useState<VideoResult[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [failed, setFailed] = useState(false);
  const [current, setCurrent] = useState(0);

  const playerHostRef = useRef<HTMLDivElement | null>(null);
  const playerRef = useRef<YTPlayer | null>(null);
  const wordTimeRef = useRef(0);

  useEffect(() => {
    let cancelled = false;
    searchVideos(word)
      .then(v => {
        if (!cancelled) setVideos(v);
      })
      .catch(() => {
        if (!cancelled) setFailed(true);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [word]);

  const retry = () => {
    setFailed(false);
    setVideos(null);
    setCurrent(0);
    setLoading(true);
    searchVideos(word)
      .then(v => setVideos(v))
      .catch(() => setFailed(true))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onClose]);

  // Create / swap the YouTube player when the active video changes
  useEffect(() => {
    const video = videos?.[current];
    if (!video || failed) return;

    let cancelled = false;

    void (async () => {
      // Find where the word is actually spoken (fallback: start of video)
      wordTimeRef.current = (await findWordTime(video.id, word)) ?? 0;
      if (cancelled) return;

      await loadYouTubeApi();
      if (cancelled || !window.YT || !playerHostRef.current) return;

      if (playerRef.current) {
        playerRef.current.loadVideoById({ videoId: video.id, startSeconds: wordTimeRef.current });
        return;
      }

      playerRef.current = new window.YT.Player(playerHostRef.current, {
        videoId: video.id,
        playerVars: {
          autoplay: 1,
          start: wordTimeRef.current,
          cc_load_policy: 1,
          cc_lang_pref: 'en',
          rel: 0,
          modestbranding: 1,
        },
        events: {
          onReady: () => playerRef.current?.playVideo(),
        },
      });
    })();

    return () => {
      cancelled = true;
    };
  }, [videos, current, word, failed]);

  // Destroy player on close
  useEffect(() => {
    return () => {
      try {
        playerRef.current?.destroy();
      } catch {
        /* noop */
      }
      playerRef.current = null;
    };
  }, []);

  const seekBy = (delta: number) => {
    const p = playerRef.current;
    if (!p) return;
    p.seekTo(Math.max(0, wordTimeRef.current + delta), true);
    p.playVideo();
  };

  const total = videos?.length ?? 0;
  const active: VideoResult | undefined = videos?.[current];
  const safeActive = active ?? { id: '', title: '', uploader: '' };
  const hasPrev = current > 0;
  const hasNext = total > 0 && current < total - 1;

  const controlBtn =
    'inline-flex cursor-pointer items-center gap-1 rounded-lg border border-white/15 px-3 py-1.5 text-xs font-bold text-gray-200 transition-all hover:border-teal-400 hover:text-teal-300 active:scale-95 disabled:cursor-not-allowed disabled:opacity-40';

  return createPortal(
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-[90] flex items-stretch justify-center bg-black/70 backdrop-blur-sm sm:items-center sm:p-6"
        onClick={onClose}
        role="dialog"
        aria-label={`Real videos using ${word}`}
      >
        <motion.div
          initial={{ scale: 0.96, y: 20, opacity: 0 }}
          animate={{ scale: 1, y: 0, opacity: 1 }}
          exit={{ scale: 0.97, opacity: 0 }}
          transition={{ type: 'spring', duration: 0.4 }}
          className="flex h-[100dvh] w-full flex-col overflow-hidden bg-[#0f172a] shadow-2xl sm:h-[92vh] sm:max-w-4xl sm:rounded-2xl sm:border sm:border-white/10"
          onClick={e => e.stopPropagation()}
        >
          {/* Header */}
          <div className="flex shrink-0 items-center justify-between gap-3 border-b border-white/10 px-4 py-3">
            <div className="flex min-w-0 items-center gap-2.5">
              <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-red-500/15 text-red-400">
                <Play className="h-4 w-4" />
              </span>
              <div className="min-w-0">
                <p className="truncate text-sm font-bold text-white">
                  <bdi>{word}</bdi>
                </p>
                <p className="flex items-center gap-1 text-[11px] text-gray-500">
                  <Subtitles className="h-3 w-3" />
                  Starts where the word is spoken · subtitles on
                </p>
              </div>
            </div>
            <button
              type="button"
              onClick={onClose}
              aria-label="Close videos"
              className="flex h-8 w-8 shrink-0 cursor-pointer items-center justify-center rounded-lg border border-white/10 text-gray-400 transition-colors hover:border-white/25 hover:text-white active:scale-95"
            >
              <X className="h-4 w-4" />
            </button>
          </div>

          {/* Body */}
          {loading ? (
            <div className="flex flex-1 flex-col items-center justify-center gap-3">
              <Loader2 className="h-8 w-8 animate-spin text-teal-400" />
              <p className="text-xs text-gray-500">Searching real videos…</p>
            </div>
          ) : failed || !videos ? (
            <div className="flex flex-1 flex-col items-center justify-center gap-3 px-6 text-center">
              <p className="text-sm font-semibold text-red-300">Couldn&apos;t find videos.</p>
              <button
                type="button"
                onClick={retry}
                className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-white/15 px-5 py-2.5 text-sm font-semibold text-gray-200 transition-colors hover:border-teal-400 hover:text-teal-300"
              >
                <RefreshCw className="h-4 w-4" />
                Try again
              </button>
            </div>
          ) : (
            <div className="flex min-h-0 flex-1 flex-col">
              {/* Player */}
              <div className="aspect-video w-full shrink-0 bg-black">
                <div ref={playerHostRef} className="h-full w-full" />
              </div>

              {/* Playback controls */}
              <div className="flex shrink-0 items-center justify-between gap-2 border-b border-white/10 px-3 py-2 sm:px-4">
                <div className="flex items-center gap-1.5">
                  <button
                    type="button"
                    onClick={() => seekBy(-5)}
                    aria-label="Back 5 seconds"
                    className={controlBtn}
                  >
                    <SkipBack className="h-4 w-4" />
                    <span className="hidden sm:inline">5s</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => seekBy(5)}
                    aria-label="Forward 5 seconds"
                    className={controlBtn}
                  >
                    <span className="hidden sm:inline">5s</span>
                    <SkipForward className="h-4 w-4" />
                  </button>
                  <button
                    type="button"
                    onClick={() => seekBy(0)}
                    aria-label="Replay from the word"
                    className={`${controlBtn} border-teal-500/40 text-teal-300 hover:border-teal-400 hover:text-teal-200`}
                  >
                    <RotateCcw className="h-4 w-4" />
                    <span className="hidden sm:inline">Replay word</span>
                  </button>
                </div>

                <div className="flex min-w-0 items-center gap-2">
                  <button
                    type="button"
                    onClick={() => hasPrev && setCurrent(i => i - 1)}
                    disabled={!hasPrev}
                    aria-label="Previous video"
                    className="flex h-8 w-8 shrink-0 cursor-pointer items-center justify-center rounded-lg border border-white/15 text-gray-200 transition-all hover:border-teal-400 hover:text-teal-300 active:scale-95 disabled:cursor-not-allowed disabled:opacity-40"
                  >
                    <ChevronLeft className="h-4 w-4" />
                  </button>
                  <span className="shrink-0 text-[11px] font-semibold tabular-nums text-gray-500">
                    {current + 1}/{total}
                  </span>
                  <button
                    type="button"
                    onClick={() => hasNext && setCurrent(i => i + 1)}
                    disabled={!hasNext}
                    aria-label="Next video"
                    className="flex h-8 w-8 shrink-0 cursor-pointer items-center justify-center rounded-lg border border-white/15 text-gray-200 transition-all hover:border-teal-400 hover:text-teal-300 active:scale-95 disabled:cursor-not-allowed disabled:opacity-40"
                  >
                    <ChevronRight className="h-4 w-4" />
                  </button>
                </div>
              </div>

              {/* Current video info */}
              <div className="shrink-0 px-4 pt-2 pb-1 text-center">
                <bdi className="block truncate text-xs font-semibold text-gray-200">
                  {safeActive.title}
                </bdi>
                <p className="truncate text-[10px] text-gray-500">{safeActive.uploader}</p>
              </div>

              {/* Results list */}
              <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain p-2">
                {videos.map((v, i) => (
                  <button
                    key={v.id}
                    type="button"
                    onClick={() => setCurrent(i)}
                    className={`flex w-full cursor-pointer items-start gap-2 rounded-xl px-3 py-2 text-left transition-colors ${
                      i === current ? 'bg-teal-500/15' : 'hover:bg-white/5'
                    }`}
                  >
                    <span
                      className={`mt-0.5 shrink-0 rounded-md px-1.5 py-0.5 text-[10px] font-bold ${
                        i === current ? 'bg-teal-500 text-white' : 'bg-white/10 text-gray-400'
                      }`}
                    >
                      {i + 1}
                    </span>
                    <span className="min-w-0">
                      <bdi
                        className={`block truncate text-xs font-medium ${
                          i === current ? 'text-teal-200' : 'text-gray-300'
                        }`}
                      >
                        {v.title}
                      </bdi>
                      <span className="block truncate text-[10px] text-gray-500">{v.uploader}</span>
                    </span>
                  </button>
                ))}
              </div>
            </div>
          )}
        </motion.div>
      </motion.div>
    </AnimatePresence>,
    document.body
  );
}
