// ─── AI / Settings ────────────────────────────────────────────────────────────

export type AIProvider =
  | 'openai'
  | 'commandcode'
  | 'openrouter'
  | 'opencode'
  | 'google'
  | 'anthropic'
  | 'cohere'
  | 'groq'
  | 'deepseek'
  | 'mistral'
  | 'xai';

export type LanguageLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1';

export type FrequencyNote = 'common' | 'formal' | 'specialized';

export interface UserSettings {
  provider: AIProvider;
  apiKey: string;
  model: string;
  theme: 'dark' | 'light';
  defaultLevel: LanguageLevel;
}

// ─── Quiz Data (generated by AI at session start) ─────────────────────────────

export interface WordQuizData {
  word: string;
  arabicMeaning: string;
  englishDefinition: string;
  exampleSentence: string;         // English sentence with ___ replacing the word
  distractors: string[];           // 3 confusable English words for MCQ rounds 1 & 2
  arabicDistractors: string[];     // 3 wrong Arabic meanings for Round 3
  sentenceDistractors: string[];   // 3 wrong words that could fit the blank (Round 4)
  collocations: string[];          // e.g. ["make a decision", "reach a decision"]
  emojiAnchor?: string;            // e.g. "🧳" for "luggage"
  frequencyNote: FrequencyNote;
  memoryTip?: string;              // Short Arabic memory tip
}

// ─── Quiz Engine ──────────────────────────────────────────────────────────────

export type RoundNumber = 1 | 2 | 3 | 4 | 5 | 6;
export type WordStatus = 'pending' | 'in-progress' | 'mastered';

export interface RoundAttempt {
  round: RoundNumber;
  correct: boolean;
  usedHint: boolean;
  timestamp: Date;
}

export interface WordProgress {
  word: string;
  quizData: WordQuizData;
  currentRound: RoundNumber;
  status: WordStatus;
  attempts: RoundAttempt[];
  xpEarned: number;
  hintsUsed: number;
}

// A single question rendered to the user
export interface QuizQuestion {
  wordProgress: WordProgress;
  round: RoundNumber;
  questionText: string;     // The question being asked
  options: string[];        // 4 options + "I don't know" (shuffled)
  correctAnswer: string;    // The right answer
  contextLine?: string;     // Optional lead-in context line
}

export type QuizPhase =
  | 'idle'
  | 'loading'      // AI generating quiz data
  | 'active'       // Quiz in progress
  | 'feedback'     // Showing feedback after answer
  | 'speed-round'  // Optional speed round
  | 'mastery'      // Optional mastery dialogue
  | 'complete';    // Session done

// ─── Active Quiz State (Zustand) ──────────────────────────────────────────────

export interface QuizState {
  phase: QuizPhase;
  words: WordProgress[];
  currentQuestion: QuizQuestion | null;
  lastAnswer: {
    selected: string;
    correct: boolean;
    feedbackText: string;
  } | null;
  xp: number;
  streak: number;
  maxStreak: number;
  level: LanguageLevel;
  sessionStartTime: Date | null;

  // Actions
  startSession: (words: string[], level: LanguageLevel, quizData: WordQuizData[]) => void;
  answerQuestion: (selected: string) => void;
  nextQuestion: () => void;
  useHint: () => string;
  setPhase: (phase: QuizPhase) => void;
  resetQuiz: () => void;
}

// ─── Settings Store (Zustand) ─────────────────────────────────────────────────

export interface SettingsState {
  provider: AIProvider;
  apiKey: string;
  model: string;
  theme: 'dark' | 'light';
  defaultLevel: LanguageLevel;
  voiceURI: string;

  // Actions
  setProvider: (provider: AIProvider) => void;
  setApiKey: (key: string) => void;
  setModel: (model: string) => void;
  setTheme: (theme: 'dark' | 'light') => void;
  setDefaultLevel: (level: LanguageLevel) => void;
  setVoiceURI: (uri: string) => void;
  clearApiKey: () => void;
}

// ─── Session History (IndexedDB via Dexie) ────────────────────────────────────

export interface SessionRecord {
  id?: number;
  date: Date;
  words: string[];
  level: LanguageLevel;
  provider: AIProvider;
  totalXP: number;
  maxPossibleXP: number;
  masteredWords: string[];
  struggledWords: string[];    // words that needed >1 attempt on any round
  errorPattern?: string;
  durationMinutes: number;
  completed: boolean;
}

// ─── Mastery Dialogue ─────────────────────────────────────────────────────────

export interface MasteryBlank {
  position: number;       // which blank (0-indexed)
  correctWord: string;
  options: string[];      // 3-4 choices including correct
}

export interface MasteryDialogue {
  dialogue: string;       // Full dialogue with ___ for blanks
  blanks: MasteryBlank[];
}

// ─── AI Response Schemas ──────────────────────────────────────────────────────

export interface AISessionDataResponse {
  words: WordQuizData[];
}

// ─── Utility types ────────────────────────────────────────────────────────────

export interface ModelOption {
  id: string;
  label: string;
}

export const PROVIDER_MODELS: Record<AIProvider, ModelOption[]> = {
  openai: [
    { id: 'gpt-4o', label: 'GPT-4o' },
    { id: 'gpt-4o-mini', label: 'GPT-4o Mini (Faster)' },
    { id: 'gpt-4-turbo', label: 'GPT-4 Turbo' },
    { id: 'gpt-4.1', label: 'GPT-4.1' },
    { id: 'gpt-4.1-mini', label: 'GPT-4.1 Mini (Faster)' },
    { id: 'o3', label: 'o3 (Reasoning)' },
    { id: 'o4-mini', label: 'o4 Mini (Reasoning, Faster)' },
  ],
  commandcode: [
    { id: 'deepseek/deepseek-v4-flash', label: 'DeepSeek V4 Flash' },
    { id: 'google/gemini-3.7-flash', label: 'Gemini 3.7 Flash' },
    { id: 'minimax-m3', label: 'MiniMax M3' },
    { id: 'mimo-v2.5', label: 'Mimo v2.5' },
    { id: 'laguna-s-2.1-free', label: 'Laguna S 2.1 Free' },
  ],
  openrouter: [
    { id: 'stealth/ox-alpha', label: 'Ox Alpha (Free)' },
    { id: 'openrouter/auto', label: 'Auto Router' },
    { id: '~openai/gpt-latest', label: 'OpenAI Latest' },
    { id: 'openai/gpt-4o', label: 'GPT-4o' },
    { id: 'openai/gpt-4o-mini', label: 'GPT-4o Mini (Cheaper)' },
    { id: 'anthropic/claude-sonnet-4', label: 'Claude Sonnet 4' },
    { id: 'anthropic/claude-3.5-sonnet', label: 'Claude 3.5 Sonnet' },
    { id: 'google/gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
    { id: 'google/gemini-2.0-flash-001', label: 'Gemini 2.0 Flash' },
    { id: 'deepseek/deepseek-chat-v3.1', label: 'DeepSeek V3.1' },
    { id: 'deepseek/deepseek-r1', label: 'DeepSeek R1 (Reasoning)' },
    { id: 'meta-llama/llama-3.3-70b-instruct', label: 'Llama 3.3 70B' },
    { id: 'meta-llama/llama-3.3-70b-instruct:free', label: 'Llama 3.3 70B (Free)' },
    { id: 'qwen/qwen-2.5-72b-instruct', label: 'Qwen 2.5 72B' },
    { id: 'qwen/qwen-2.5-72b-instruct:free', label: 'Qwen 2.5 72B (Free)' },
    { id: 'mistralai/mistral-small-24b-instruct-2501:free', label: 'Mistral Small 3 (Free)' },
    { id: 'google/gemma-2-9b-it:free', label: 'Gemma 2 9B (Free)' },
  ],
  opencode: [
    { id: 'code-supernova', label: 'Code Supernova' },
    { id: 'grok-code', label: 'Grok Code (Fast)' },
    { id: 'qwen3-coder', label: 'Qwen3 Coder' },
    { id: 'claude-sonnet-4', label: 'Claude Sonnet 4' },
    { id: 'gpt-5', label: 'GPT-5' },
  ],
  google: [
    { id: 'gemini-flash-latest', label: 'Gemini Flash Latest' },
    { id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
    { id: 'gemini-2.0-flash', label: 'Gemini 2.0 Flash' },
    { id: 'gemini-2.0-flash-lite', label: 'Gemini 2.0 Flash Lite (Cheapest)' },
    { id: 'gemini-1.5-pro', label: 'Gemini 1.5 Pro' },
    { id: 'gemini-1.5-flash', label: 'Gemini 1.5 Flash (Faster)' },
  ],
  anthropic: [
    { id: 'claude-sonnet-4-5', label: 'Claude Sonnet 4.5' },
    { id: 'claude-opus-4-1', label: 'Claude Opus 4.1 (Strongest)' },
    { id: 'claude-3-7-sonnet-latest', label: 'Claude 3.7 Sonnet' },
    { id: 'claude-3-5-sonnet-latest', label: 'Claude 3.5 Sonnet' },
    { id: 'claude-3-5-haiku-latest', label: 'Claude 3.5 Haiku (Faster)' },
  ],
  cohere: [
    { id: 'command-a-03-2025', label: 'Command A (Strongest)' },
    { id: 'command-r-plus', label: 'Command R+' },
    { id: 'command-r-08-2024', label: 'Command R' },
    { id: 'command-r7b-12-2024', label: 'Command R7B (Faster)' },
  ],
  groq: [
    { id: 'llama-3.3-70b-versatile', label: 'Llama 3.3 70B Versatile' },
    { id: 'llama-3.1-8b-instant', label: 'Llama 3.1 8B (Instant)' },
    { id: 'openai/gpt-oss-120b', label: 'GPT-OSS 120B' },
    { id: 'openai/gpt-oss-20b', label: 'GPT-OSS 20B (Fast)' },
    { id: 'gemma2-9b-it', label: 'Gemma 2 9B' },
    { id: 'qwen/qwen3-32b', label: 'Qwen 3 32B' },
  ],
  deepseek: [
    { id: 'deepseek-chat', label: 'DeepSeek V3 Chat' },
    { id: 'deepseek-reasoner', label: 'DeepSeek R1 (Reasoning)' },
  ],
  mistral: [
    { id: 'mistral-large-latest', label: 'Mistral Large' },
    { id: 'mistral-small-latest', label: 'Mistral Small' },
    { id: 'open-mistral-nemo', label: 'Mistral Nemo' },
    { id: 'codestral-latest', label: 'Codestral' },
    { id: 'ministral-8b-latest', label: 'Ministral 8B (Fast)' },
  ],
  xai: [
    { id: 'grok-4', label: 'Grok 4 (Strongest)' },
    { id: 'grok-3', label: 'Grok 3' },
    { id: 'grok-3-mini', label: 'Grok 3 Mini (Faster)' },
    { id: 'grok-2-1212', label: 'Grok 2' },
  ],
};

export const LEVEL_DESCRIPTIONS: Record<LanguageLevel, string> = {
  A1: 'Total beginner',
  A2: 'Elementary',
  B1: 'Intermediate',
  B2: 'Upper-intermediate',
  C1: 'Advanced',
};
