// ─── AI / Settings ────────────────────────────────────────────────────────────

export type AIProvider = 'openai' | 'commandcode' | 'openrouter' | 'google' | 'anthropic' | 'cohere';

export type LanguageLevel = 'A1' | 'A2' | 'B1' | 'B2' | 'C1';

export type FrequencyNote = 'common' | 'formal' | 'specialized';

export interface UserSettings {
  provider: AIProvider;
  apiKey: string;
  model: string;
  theme: 'dark' | 'light';
  defaultLevel: LanguageLevel;
}

// ─── Quiz Data (generated by AI at session start) ─────────────────────────────

export interface WordQuizData {
  word: string;
  arabicMeaning: string;
  englishDefinition: string;
  exampleSentence: string;         // English sentence with ___ replacing the word
  distractors: string[];           // 3 confusable English words for MCQ rounds 1 & 2
  arabicDistractors: string[];     // 3 wrong Arabic meanings for Round 3
  sentenceDistractors: string[];   // 3 wrong words that could fit the blank (Round 4)
  collocations: string[];          // e.g. ["make a decision", "reach a decision"]
  emojiAnchor?: string;            // e.g. "🧳" for "luggage"
  frequencyNote: FrequencyNote;
  memoryTip?: string;              // Short Arabic memory tip
}

// ─── Quiz Engine ──────────────────────────────────────────────────────────────

export type RoundNumber = 1 | 2 | 3 | 4;
export type WordStatus = 'pending' | 'in-progress' | 'mastered';

export interface RoundAttempt {
  round: RoundNumber;
  correct: boolean;
  usedHint: boolean;
  timestamp: Date;
}

export interface WordProgress {
  word: string;
  quizData: WordQuizData;
  currentRound: RoundNumber;
  status: WordStatus;
  attempts: RoundAttempt[];
  xpEarned: number;
  hintsUsed: number;
}

// A single question rendered to the user
export interface QuizQuestion {
  wordProgress: WordProgress;
  round: RoundNumber;
  questionText: string;     // The question being asked
  options: string[];        // 4 options + "I don't know" (shuffled)
  correctAnswer: string;    // The right answer
  contextLine?: string;     // Optional lead-in context line
}

export type QuizPhase =
  | 'idle'
  | 'loading'      // AI generating quiz data
  | 'active'       // Quiz in progress
  | 'feedback'     // Showing feedback after answer
  | 'speed-round'  // Optional speed round
  | 'mastery'      // Optional mastery dialogue
  | 'complete';    // Session done

// ─── Active Quiz State (Zustand) ──────────────────────────────────────────────

export interface QuizState {
  phase: QuizPhase;
  words: WordProgress[];
  currentQuestion: QuizQuestion | null;
  lastAnswer: {
    selected: string;
    correct: boolean;
    feedbackText: string;
  } | null;
  xp: number;
  streak: number;
  maxStreak: number;
  level: LanguageLevel;
  sessionStartTime: Date | null;

  // Actions
  startSession: (words: string[], level: LanguageLevel, quizData: WordQuizData[]) => void;
  answerQuestion: (selected: string) => void;
  nextQuestion: () => void;
  useHint: () => string;
  setPhase: (phase: QuizPhase) => void;
  resetQuiz: () => void;
}

// ─── Settings Store (Zustand) ─────────────────────────────────────────────────

export interface SettingsState {
  provider: AIProvider;
  apiKey: string;
  model: string;
  theme: 'dark' | 'light';
  defaultLevel: LanguageLevel;

  // Actions
  setProvider: (provider: AIProvider) => void;
  setApiKey: (key: string) => void;
  setModel: (model: string) => void;
  setTheme: (theme: 'dark' | 'light') => void;
  setDefaultLevel: (level: LanguageLevel) => void;
  clearApiKey: () => void;
}

// ─── Session History (IndexedDB via Dexie) ────────────────────────────────────

export interface SessionRecord {
  id?: number;
  date: Date;
  words: string[];
  level: LanguageLevel;
  provider: AIProvider;
  totalXP: number;
  maxPossibleXP: number;
  masteredWords: string[];
  struggledWords: string[];    // words that needed >1 attempt on any round
  errorPattern?: string;
  durationMinutes: number;
  completed: boolean;
}

// ─── Mastery Dialogue ─────────────────────────────────────────────────────────

export interface MasteryBlank {
  position: number;       // which blank (0-indexed)
  correctWord: string;
  options: string[];      // 3-4 choices including correct
}

export interface MasteryDialogue {
  dialogue: string;       // Full dialogue with ___ for blanks
  blanks: MasteryBlank[];
}

// ─── AI Response Schemas ──────────────────────────────────────────────────────

export interface AISessionDataResponse {
  words: WordQuizData[];
}

// ─── Utility types ────────────────────────────────────────────────────────────

export interface ModelOption {
  id: string;
  label: string;
}

export const PROVIDER_MODELS: Record<AIProvider, ModelOption[]> = {
  openai: [
    { id: 'gpt-4o', label: 'GPT-4o' },
    { id: 'gpt-4o-mini', label: 'GPT-4o Mini (Faster)' },
    { id: 'gpt-4-turbo', label: 'GPT-4 Turbo' },
  ],
  commandcode: [
    { id: 'deepseek/deepseek-v4-flash', label: 'DeepSeek V4 Flash' },
    { id: 'google/gemini-3.7-flash', label: 'Gemini 3.7 Flash' },
    { id: 'minimax-m3', label: 'MiniMax M3' },
    { id: 'mimo-v2.5', label: 'Mimo v2.5' },
    { id: 'laguna-s-2.1-free', label: 'Laguna S 2.1 Free' },
  ],
  openrouter: [
    { id: '~openai/gpt-latest', label: 'OpenAI Latest' },
    { id: 'openrouter/auto', label: 'Auto Router' },
    { id: 'openai/gpt-4o', label: 'GPT-4o' },
    { id: 'anthropic/claude-sonnet-4', label: 'Claude Sonnet 4' },
    { id: 'google/gemini-2.5-flash', label: 'Gemini 2.5 Flash' },
  ],
  google: [
    { id: 'gemini-flash-latest', label: 'Gemini Flash Latest' },
    { id: 'gemini-2.0-flash', label: 'Gemini 2.0 Flash' },
    { id: 'gemini-1.5-pro', label: 'Gemini 1.5 Pro' },
    { id: 'gemini-1.5-flash', label: 'Gemini 1.5 Flash (Faster)' },
  ],
  anthropic: [
    { id: 'claude-3-5-sonnet-latest', label: 'Claude 3.5 Sonnet' },
    { id: 'claude-3-haiku-20240307', label: 'Claude 3 Haiku (Faster)' },
  ],
  cohere: [
    { id: 'command-a-03-2025', label: 'Command A' },
    { id: 'command-r-plus', label: 'Command R+ (Stronger)' },
    { id: 'command-r', label: 'Command R (Faster)' },
  ],
};

export const LEVEL_DESCRIPTIONS: Record<LanguageLevel, string> = {
  A1: 'Total beginner',
  A2: 'Elementary',
  B1: 'Intermediate',
  B2: 'Upper-intermediate',
  C1: 'Advanced',
};
